# Generated by Django 3.0.7 on 2022-02-17 11:27

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220216_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMultipleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipleimages', models.FileField(blank=True, null=True, upload_to=core.models.get_file_name)),
                ('item_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
    ]
