# Generated by Django 3.0.7 on 2022-02-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_itemmultipleimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
